[book]
authors = ["Tyler Swann"]
title = "The C++ Programming Language"
description = "The C++ Programming Language"

language = "en"

src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/oraqlle/cpp-book"
additional-css = ["./whichlang.css"]
additional-js = ["./whichlang.js"]
hash-files = true

[output.html.playground]
editable = true

[output.html.code.hidelines]
cpp = "$"

